module.exports = {
  GET_STARTED: 'GET_STARTED',
  REPORT: 'REPORT',
  FOLLOW_UP: 'FOLLOW_UP',
  ADD_DETAILS_YES: 'ADD_DETAILS_YES',
  ADD_DETAILS_NO: 'ADD_DETAILS_NO',
  MAKE_REPORT_YES: 'MAKE_REPORT_YES',
  MAKE_REPORT_NO: 'MAKE_REPORT_NO'
}
